### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by fingolfin** [bh11/irredsol#2]
I was about to suggest to use `TestDirectory` in this package, but I see this is already the case in the master branch. Great! So I'd like to request that a new release be made, with this change in, so that we can simplify the code in the GAP distribution which detects whether the tests of a package passed.

Thanks!

**Comment by bh11** [comment]
> On 02 Aug 2017, at 18:19, Max Horn <notifications@github.com> wrote:
> 
> I was about to suggest to use TestDirectory in this package, but I see this is already the case in the master branch. Great! So I'd like to request that a new release be made, with this change in, so that we can simplify the code in the GAP distribution which detects whether the tests of a package passed.

The current release (1.3.1) already uses TestDirectory.

Cheers

Burkhard.

**Comment by fingolfin** [comment]
Sorry for the confusion, I should have looked more carefully. What I really would like is that this is used (which is what is in the repository):
```
 TestDirectory(DirectoriesPackageLibrary("irredsol", "tst"),
    rec(exitGAP := true));
```
I.e. with the `exitGap` option -- which is *not* used in 1.3.1

In addition, you can also get rid of the renormalisation code -- GAP stones have been abolished.

**Comment by bh11** [comment]
I've decided to release version 1.4, rather than to backport the changes to 1.3. (Still a possibility if it breaks anything serious). The new release is just being picked up, should be available shortly.
