### ISSUE TITLE
Modify release script to compress data files

### ISSUE THREAD

**Issue by fingolfin** [bh11/irredsol#20]
It would be great if you could ship the data files in `data` and `fp` as gzip files inside the irredsol.tar.gz.

I.e., before putting them into the archive, run `gzip` (or even `gzip -9`) on them. For me, this reduces disk usage for the `fp` plus `data` directory from 71.5 MB to 25.5 MB (with PR #19: from 58 MB to 25 MB). 

While disk space is cheap these days, some people still need to use GAP in lab environments with home dirs on NFS with limited quota, so having this smaller is helpful.

**Comment by bh11** [comment]
Thanks for the suggestion. I’ll use gzipped data files in the next release. This also makes PR #19 unneccessary.

**Comment by fingolfin** [comment]
Any estimate when the next release will be? Would be nice to have the changes available to users. Next GAP release will be in mid December

**Comment by bh11** [comment]
Good to know about December. I’ve just released a new version with the recent changes.
