### ISSUE TITLE
Loading Errors regarding 'DegreeOfMatrixGroup'

### ISSUE THREAD

**Issue by algorithmx** [bh11/irredsol#5]
(base) dabajabaza@XXXX:~$ gap
 ┌───────┐   GAP 4.10.0 of 01-Nov-2018
 │  GAP         │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64
 Configuration:  gmp 6.1.2, readline
 Loading the library and packages ...
Error, Variable: 'DegreeOfMatrixGroup' must have a value
not in any function at /usr/lib/gap/pkg/irredsol-1.4/lib/matmeths.gi:16
Error, was not in any namespace at /usr/share/gap/lib/variable.g:291 called from
LEAVE_NAMESPACE(  ); at /usr/share/gap/lib/package.gi:1255 called from
ReadPackage( "irredsol", path ) at /usr/lib/gap/pkg/irredsol-1.4/init.g:9 called from
<function "IRREDSOL_Read">( <arguments> )
 called from read-eval loop at /usr/lib/gap/pkg/irredsol-1.4/read.g:9
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> return;
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/iterato\
rs.gi:246
                [[Degree, DegreeOfMatrixGroup, Dimension, DimensionOfMatrixGroup], I\
sPosInt],
                                             ^
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/iterato\
rs.gi:251
                 [[IsPrimitive, IsPrimitiveMatrixGroup, IsLinearlyPrimitive], x -> x\
 in [true, false]],
                                                                           ^
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/recogni\
ze.gi:20
                DegreeOfMatrixGroup(G), Size(TraceField(G)));
                                   ^
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/recogni\
ze.gi:35
                DegreeOfMatrixGroup(G), Size(TraceField(G)));
                                   ^
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/recogni\
ze.gi:563
    n := DegreeOfMatrixGroup(H);
                            ^
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/recogni\
ze.gi:649
        n := DegreeOfMatrixGroup(G);
                                ^
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/recogni\
ze.gi:764
                        DegreeOfMatrixGroup(G), Size(F), 1, inds, [Order(G)], 
                                           ^
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/recogni\
ze.gi:774
                H := IrreducibleSolubleMatrixGroup(DegreeOfMatrixGroup(G), Size(F), \
1, inds[i]);
                                                                      ^
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/recogni\
ze.gi:795
                    info.id := [DegreeOfMatrixGroup(G), Size(F), 1, inds[i]];
                                                   ^
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/recogni\
ze.gi:814
        info.id := [DegreeOfMatrixGroup(G), Size(F), 1, i];
                                       ^
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/recogni\
ze.gi:819
        H := IrreducibleSolubleMatrixGroup(DegreeOfMatrixGroup(G), Size(F), 1, i);
                                                              ^
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/recogni\
ze.gi:935
                newinfo := rec(id := [DegreeOfMatrixGroup(G), Size(TraceField(G)), 1\
, info.id[4]]);
                                                         ^
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/recogni\
ze.gi:963
            d := DegreeOfMatrixGroup(G)/MTX.Dimension (module);
                                    ^
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/recogni\
ze.gi:988
                    DegreeOfMatrixGroup(G), q, d, info.id[4]);
                                       ^
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/recogni\
ze.gi:991
                id := [DegreeOfMatrixGroup(G), q, d, info.id[4]^(perm_pow.perm^perm_\
pow.pow)]);
                                          ^
Syntax warning: Unbound global variable in /usr/lib/gap/pkg/irredsol-1.4/lib/primiti\
ve.gi:36
        d := DegreeOfMatrixGroup(Range(hom));
                                ^
Error, was not in any namespace at /usr/share/gap/lib/variable.g:291 called from
LEAVE_NAMESPACE(  ); at /usr/share/gap/lib/package.gi:1340 called from
LoadPackage_ReadImplementationParts( secondrun, banner 
 ); at /usr/share/gap/lib/package.gi:1636 called from
LoadPackage( name, false ) at /usr/share/gap/lib/package.gi:1930 called from
func(  ); at /usr/share/gap/lib/system.g:213 called from
<function "CallAndInstallPostRestore">( <arguments> )
 called from read-eval loop at /usr/share/gap/lib/init.g:765
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> return;
 Packages:   Alnuth 3.1.0, AtlasRep 1.5.1, AutPGrp 1.10, CRISP 1.4.4, CTblLib 1.2.2, 
             FactInt 1.6.2, FGA 1.4.0, GAPDoc 1.6.2, IO 4.5.4, IRREDSOL 1.4, 
             LAGUNA 3.9.3, Polycyclic 2.14, PrimGrp 3.3.2, SmallGrp 1.3, 
             Sophus 1.24, TomLib 1.2.7, TransGrp 2.0.4
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap>

**Comment by bh11** [comment]
Sorry, I can't reproduce your problem using a fresh copy of GAP 4.10.0 (and it has never shown up on any of our automatic GAP test setups). The only thing I noticed is that the IRREDSOL package seems to be loaded from /usr/lib/gap while the remaining GAP installation originates from /usr/share/gap. So maybe two GAP versions got mixed up? (You may want to try starting GAP with the -r option to override any .gaprc file.)

If that doesn't resolve the issue, can you start GAP with the -D option and post the output as well as the contents of the GAPInfo variable?

**Comment by fingolfin** [comment]
`DegreeOfMatrixGroup` is not defined in GAP, it is defined in the `primgrp` package. And IRREDSOL does not have a dependency on `DegreeOfMatrixGroup`. Now since `primgrp` is a required GAP package, it normally is always loaded, so this is no problem.

Unfortunately, some downstream packagers for Linux distributions like to mess with our stuff and turn required packages into non-required, thus introducing bugs like this one...

@algorithmx could you tell us how you installed GAP? Also, which Linux distribution are you using?

BTW, regardless of everything else: GAP 4.10.0 is outdated and contains known bugs, I'd suggest to use 4.10.2 instead (but of course if you installed it via some package manager, that might not be an option for you, unless you are willing to compile GAP yourself...)

**Comment by olexandr-konovalov** [comment]
@fingolfin btw, shall we add  "primgrp" as required package for IRREDSOL to document this dependency? (cf. https://github.com/gap-system/gap/issues/2434)

**Comment by bh11** [comment]
Removed the dependency on primgrp in IRREDSOL-1.4.1. Probably the definition from primgrp should be part of the GAP library anyway.
